config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'main#index'

  # resources :orders
  get '/orders/new', to: 'orders#new', as: 'new_order'
  post '/orders', to: 'orders#create'
  get '/orders/order_simple', to: 'orders#order_simple'
  get '/orders/get_items', to: 'orders#get_items', as: 'get_items'
  get '/orders/get_sidebar', to: 'orders#get_sidebar', as: 'get_sidebar'

  get '/category/:category', to: 'main#show', as: 'show'
  get '/all_products', to: 'main#all_cats', as: 'all_cats'
  get '/search', to: 'main#search', as: 'search'
  get '/about', to: 'main#about', as: 'about'

  get  'cards/new/:category_id',  to: 'cards#new',  as: :new_card
  post 'cards/create_image/:temp_key/:type', to: 'cards#create_image', as: :create_image
  post 'cards/update_image/:id/:type', to: 'cards#update_image', as: :update_image_card

  post '/parse_card_items', to: 'card_items#parse_data', as: :parse_card_items

  resources :news, only: [:index, :show]

  resources :clients, only: [:signin]
  get '/login', to: 'clients#login', as: :login
  post '/signin', to: 'clients#signin', as: :signin

  resources :cards, only: [:create, :edit, :update, :destroy] do
    collection do
      post 'sort'
    end
  end

  resources :card_items, only: [:destroy]
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # @promo_cards = PromoCard.all
    card_ids = Card.ids.shuffle(random: Random.new(Time.now.to_i))
    @cards = Card.where(id: card_ids)
  end

  def show
    category = params[:category]
    @category = Category.includes(:cards).find_by_id category
    if @category
      @cards = @category.cards.includes(:card_items, :tags)
    else
      redirect_to root_path
    end
  end

  def all_cats
    @categories = Category.all.includes(:cards)
  end

  def search
    if params[:tag]
      @cards = Card.tagged_with params[:tag]
      @category = @cards.first.category
    else
      redirect_to root_path
    end
  end

  def about
  end
end

app/views/main/_card.html.slim
- card ||= @card

.card class=(card.big? ? 'double' : '') data-card-id=card.id data-priority=card.priority data-edit-url=edit_card_path(card.id, format: :json)
  - if admin_user_signed_in?
    = link_to card, class: 'del-icon', method: :delete, data: { confirm: 'Вы уверены?' }, remote: true do
      svg[xmlns="http://www.w3.org/2000/svg" viewbox="0 0 340.1 340.1" width="512" height="512"]
        path[d="M306.1 45.4l-68-0.3V36.6c0-20.2-18.5-36.6-41.4-36.6h-53.1c-22.9 0-41.5 16.4-41.5 36.6v8.7l-68 0v45.4h23.4c-0.4 3.6-0.7 7.3-0.7 11v181.6c0 29.9 14.5 56.8 45.4 56.8h136.1c30.8 0 45.4-26.9 45.4-56.8V101.8c0-3.7-0.2-7.4-0.5-11h23.1C306.1 90.8 306.1 45.4 306.1 45.4zM124.7 36.6c0-7.6 8.6-13.9 18.8-13.9h53.1c10.2 0 18.8 6.4 18.8 13.9v8.7h-90.7v-8.7H124.7zM260.8 283.3c0 17.4-4.3 34.1-22.7 34.1H102c-18.3 0-22.7-16.6-22.7-34.1v-181.6c0-3.8 0.2-7.5 0.8-11h179.9c0.5 3.5 0.8 7.2 0.8 11v181.6H260.8zM102 294.8h22.7V113.4h-22.7V294.8zM158.7 294.8h22.7V113.4h-22.7V294.8zM215.4 294.8h22.7V113.4h-22.7V294.8z" fill="#c9c9c9"]
    .edit-icon
      svg[xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewbox="0 0 32 32"]
        path[d="M30.3 1.7C29.2 0.6 27.7 0 26.1 0s-3 0.6-4.2 1.7L4.3 19.3c-0.1 0.1-0.2 0.2-0.2 0.4l-4 11c-0.1 0.4 0 0.8 0.2 1C0.5 31.9 0.7 32 1 32c0.1 0 0.2 0 0.3 0l9.9-3.1c0.2 0 0.3-0.1 0.4-0.2l18.6-18.6C31.4 8.9 32 7.4 32 5.9 32 4.3 31.4 2.8 30.3 1.7zM10.1 27.2l-3.7 1.1c-0.2-0.6-0.6-1.2-1-1.7 -0.4-0.4-0.9-0.7-1.4-1L5.7 21H8v2c0 0.6 0.4 1 1 1h1.8L10.1 27.2zM24.8 12.7L12.6 24.9l0.4-1.6c0.1-0.3 0-0.6-0.2-0.8C12.6 22.1 12.3 22 12 22h-2v-2c0-0.6-0.4-1-1-1H7.4L19.3 7.2l0 0c0.7-0.7 1.7-1.1 2.7-1.1s2 0.4 2.7 1.1 1.1 1.7 1.1 2.7C25.9 11 25.5 11.9 24.8 12.7zM28.9 8.6L27.9 9.6c-0.1-1.4-0.7-2.8-1.7-3.8 -1-1-2.4-1.6-3.8-1.7l0.9-0.9 0 0C24.1 2.4 25.1 2 26.1 2s2 0.4 2.7 1.1C29.6 3.9 30 4.8 30 5.9 30 6.9 29.6 7.9 28.9 8.6zM22.3 8.3l-10 10c-0.4 0.4-0.4 1 0 1.4C12.5 19.9 12.7 20 13 20s0.5-0.1 0.7-0.3l10-10c0.4-0.4 0.4-1 0-1.4C23.3 7.9 22.7 7.9 22.3 8.3z" fill="#c9c9c9"]
  - if !card.image.blank?
    .card-photo class=(card.image_style ? 'vertical' : '')
      = image_tag card.image, class: "card-main-photo"
    .hover-slider
      - card.card_items.each do |item|
        = image_tag item.image, class: 'hover-slide', data: { id: "item-#{item.id}" } if !item.image.blank?
  - else
    .card-sub-photo
      - if photos = card.card_items.map{|i| i.image_url}
        = image_tag photos.first, class: 'card-main-photo' if photos.first
      .hover-slider
        - card.card_items.each do |item|
          = image_tag item.image, class: 'hover-slide', data: { id: "item-#{item.id}" } if !item.image.blank?
  .card-content
    .card-header
      h3
        = card.title
    .card-items
      - card.card_items.each do |item|
        = render 'main/card_item.html', locals: { item: item }
    .card-tags
      = card.tags.map{|tag| link_to tag.name, search_path(tag: tag.name)}.join(', ').html_safe
    - unless card.card_logo.blank?
      .card-logo
        = image_tag card.card_logo

app/views/main/_card_item.html.slim
- item = locals[:item]

a.card-item id="item-#{item.id}" href="#"
  .checkmark
  .item
    span.item-name
      = item.name
    - item.meta.split(';').each do |meta|
      span.item-unit
        nobr
          = meta
  - if !item.price.blank?
    .item-price
      - if item.kilo?
        span.item-price-value data-amount=(item.price.to_f * item.weight.to_f)
          = item.price.to_s
        span.rouble
          | ₽/кг
      - else
        span.item-price-value data-amount=item.price.to_f
          = item.price
        span.rouble
          | ₽

app/views/main/about.html.slim
article
  .about-page
    .about-page__title

    .about-page__main
      .about-page__content
        h1
          | Всегда вовремя
        p
          | «Вилком» доставляет продукты питания в магазины, отели и рестораны на территории Большого Сочи с 2000 года.
        p
          | Заказы, принятые до 10:00, доставляем по Сочи в этот же день, остальные — на следующий. В Лазаревское, Вардане, Лоо, Хосту, Адлер и Красную Поляну ездим раз в неделю по расписанию.
        .about-image
        p
          | Для нас главное — качество продуктов. Мы покупаем их у надёжных поставщиков по прямым дистрибьюторским контрактам. Храним в холодильниках промышленного класса. Перевозим в автомобилях с изотермическими кузовами и рефрижераторными установками.
        p
          | У нас нормальный сервис — удобный онлайн-заказ, внимательные операторы, вежливые и опрятные экспедиторы.
        p
          | И конечно, мы предоставляем полный комплект документов: товарные накладные, счета-фактуры, кассовые чеки, сертификаты и ветпечати.
    .about-page__news
      - Post.all.each do |post|
        = render 'news/news_preview', post: post

app/views/main/all_cats.html.slim
article
  
  h1 Все продукты
  p Это полный каталог продуктов, доступных для заказа через сайт. Вы можете сформировать заказ, выбирая продукты в каталоге, а можете оставить заявку в свободной форме, и мы вам перезвоним для уточнения деталей.
  .categories-menu
    - Category.all.each do |cat|
      - if cat.name != "Все продукты"
        .categories-menu-item
          a.scroll-link href="##{cat.id}"
            = cat.name
  - @categories.each do |cat|
    - if cat.name != "Все продукты"
      .category id=cat.id
        h2
          = cat.name
        .category-menu
          = all_tags cat
        .cards
          - cat.cards.each do |card|
            = render 'card', card: card

app/views/main/index.slim
article
  
  h1 Доставка продуктов питания в магазины, отели и рестораны Сочи, Лазаревского, Аше, Вардане, Лоо, Хосты, Адлера и Красной Поляны
  p
    a.phone-picture[href="tel:89388881212"]
      = image_tag 'phone-brown.svg', style: 'width: 200px'
  p
    a[href="/about"] О компании


  

app/views/main/search.html.slim
article
  .category id="category-#{@category.id}"
    .cards
      - @cards.each do |card|
        = render 'card', card: card

app/views/main/show.html.slim
article
  .category id="category-#{@category.id}"
    h1
      = @category.name
    .category-menu
      = all_tags @category
    .cards id=('cards_sortable' if admin_user_signed_in?) data-sort-url=sort_cards_path
      - if admin_user_signed_in?
        = render 'cards/add_card', category: @category
      - @cards.each do |card|
        = render 'card', card: card