config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'main#index'

  # resources :orders
  get '/orders/new', to: 'orders#new', as: 'new_order'
  post '/orders', to: 'orders#create'
  get '/orders/order_simple', to: 'orders#order_simple'
  get '/orders/get_items', to: 'orders#get_items', as: 'get_items'
  get '/orders/get_sidebar', to: 'orders#get_sidebar', as: 'get_sidebar'

  get '/category/:category', to: 'main#show', as: 'show'
  get '/all_products', to: 'main#all_cats', as: 'all_cats'
  get '/search', to: 'main#search', as: 'search'
  get '/about', to: 'main#about', as: 'about'

  get  'cards/new/:category_id',  to: 'cards#new',  as: :new_card
  post 'cards/create_image/:temp_key/:type', to: 'cards#create_image', as: :create_image
  post 'cards/update_image/:id/:type', to: 'cards#update_image', as: :update_image_card

  post '/parse_card_items', to: 'card_items#parse_data', as: :parse_card_items

  resources :news, only: [:index, :show]

  resources :clients, only: [:signin]
  get '/login', to: 'clients#login', as: :login
  post '/signin', to: 'clients#signin', as: :signin

  resources :cards, only: [:create, :edit, :update, :destroy] do
    collection do
      post 'sort'
    end
  end

  resources :card_items, only: [:destroy]
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = Post.all.order(created_at: :desc)
  end

  def show
    @new = Post.find_by id: params[:id]
    if !@new
    	@new = Post.find_by url: params[:id]
    end
    if !@new
      redirect_to news_index_path
    end
  end
end

app/views/news/_news_preview.slim
.post-preview
  .post-preview__header
    - title = Nokogiri::HTML.fragment(post.title).css('a')
    = title.to_s.html_safe
  = link_to news_path(id: post.get_alias) do
    .post-preview__images
      - post.post_images.first(4).each do |image|
        .post-preview__image
          = image_tag image.image

app/views/news/index.slim
article
  .news-page--index
    = render partial: 'news/news_preview', collection: @news, as: :post

app/views/news/show.slim
article.news-page
  .news-page__title
    = strip_tags(@new.title)
  .news-page__meta
    .news-date
      = I18n.localize(@new.created_at, :format => :month)
    - @new.categories.each do |category|
      .news-category
        = link_to category.name, show_path(category.id)
  - if @new.post_images.present?
    .news-page__slider
      .fotorama data-arrows="true" data-click="true" data-nav="thumbs" data-loop="true" data-width="900" data-maxwidth="100%" data-ratio="16/9"
        - @new.post_images.each do |image|
          = image_tag image.image.url
  .news-page__content
    = @new.first_text_section.html_safe
  .news-page__footer
    .news-page__more-section
      - Post.last(3).each do |post|
        = render 'news/news_preview', post: post
      = link_to 'Все новости', news_index_path, class: 'underlined'
    .news-page__categories-section
      - @new.categories.each do |category|
        = link_to category.name, show_path(category.id)