config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root to: 'main#index'

  # resources :orders
  get '/orders/new', to: 'orders#new', as: 'new_order'
  post '/orders', to: 'orders#create'
  get '/orders/order_simple', to: 'orders#order_simple'
  get '/orders/get_items', to: 'orders#get_items', as: 'get_items'
  get '/orders/get_sidebar', to: 'orders#get_sidebar', as: 'get_sidebar'

  get '/category/:category', to: 'main#show', as: 'show'
  get '/all_products', to: 'main#all_cats', as: 'all_cats'
  get '/search', to: 'main#search', as: 'search'
  get '/about', to: 'main#about', as: 'about'

  get  'cards/new/:category_id',  to: 'cards#new',  as: :new_card
  post 'cards/create_image/:temp_key/:type', to: 'cards#create_image', as: :create_image
  post 'cards/update_image/:id/:type', to: 'cards#update_image', as: :update_image_card

  post '/parse_card_items', to: 'card_items#parse_data', as: :parse_card_items

  resources :news, only: [:index, :show]

  resources :clients, only: [:signin]
  get '/login', to: 'clients#login', as: :login
  post '/signin', to: 'clients#signin', as: :signin

  resources :cards, only: [:create, :edit, :update, :destroy] do
    collection do
      post 'sort'
    end
  end

  resources :card_items, only: [:destroy]
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :category
  has_many :card_items

  mount_uploader :image, ImageUploader
  mount_uploader :card_logo, LogoUploader

  default_scope -> {order("priority ASC, created_at DESC")}

  as_enum :size, small: 0, big: 1

  acts_as_taggable
  acts_as_taggable_on :tag_list

  accepts_nested_attributes_for :card_items, reject_if: :all_blank, allow_destroy: true

  after_create :bind_photos

  private
  def bind_photos
    images = Image.where(temp_key: temp_key).all
    images.each do |image|
      if image.image_type == 'image'
        self.image = Rails.root.join(image.file.path).open
      else
        self.card_logo = Rails.root.join(image.file.path).open
      end
      image.delete
      self.save
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:create_image, :update_image]

  before_filter do
    redirect_to root_path if !admin_user_signed_in?
  end
  before_action :set_card, only: [:edit, :update, :update_image]

  def new
    @card = Card.new
    @card.category_id = params[:category_id]
    @card.temp_key = get_temp_key
    @card.card_items.build
    @tags = Card.all_tags.pluck(:name).join(",")
    respond_to do |format|
      format.html {}
      format.json {render json: { html: render_to_string('create', layout: false), status: "success"}}
    end
  end

  def create
    @card = Card.new card_params
    respond_to do |format|
      if @card.save
        format.json { render json: {html: render_to_string('main/_card.html', layout: false), id: @card.id, status: "success"}}
      end
    end
  end

  def edit
    @tags = ""
    @counter = 0
    @tags = Card.all_tags.pluck(:name).join(",")
    respond_to do |format|
      format.html {}
      format.json {render json: { html: render_to_string('edit', layout: false), status: "success"}}
    end
  end

  def update
    respond_to do |format|
      @card.assign_attributes(card_params)
      if @card.save
        format.json { render json: {html: render_to_string('main/_card.html', layout: false), id: @card.id, status: "success"}}
      end
    end
  end

  def update_image
    if params[:card_item].present?
      card_item = @card.card_items.find_by(id: params[:card_item])
      card_item.image = params[:file]
      card_item.save
    else
      if params[:type] == 'image'
        @card.image = params[:file]
      elsif !params[:type].include?('delete')
        @card.card_logo = params[:file]
      end
    end
    if params[:type] == 'delete_logo'
      @card.remove_card_logo!
    elsif params[:type] == 'delete_image'
      @card.remove_image!
    elsif params[:type] == 'delete_subimg'
      #binding.pry
      card_item = @card.card_items.find(params[:card_item])
      card_item.remove_image!
      card_item.save
    end
    @card.save
    render json: @card
  end

  def create_image
    @image = Image.new({file: params[:file], temp_key: params[:temp_key], image_type: params[:type]})
    @image.save
    render json: @image
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    respond_to do |format|
      format.html { redirect_to all_cats_url }
      format.js   { render :layout => false }
    end
  end

  def sort
    ids = params[:ids]
    @cards = Card.find(ids)
    @cards.each do |card|
      position = ids.find_index card.id.to_s
      card.update(priority: position)
    end
    @cards = @cards.sort_by(&:priority)
    render json: @cards
  end

  private
  def get_temp_key
    o = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
    (0...50).map { o[rand(o.length)] }.join
  end

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:title, :image_style, :tag_list, :category_id, :temp_key, :size_cd, card_items_attributes: card_items_attributes)
  end

  def card_items_attributes
      [:id, :name, :meta,:price,:prirority,:image,:temp_key, :units, :vendor_code, :weight]
  end
end

app/views/cards/_add_card.slim
.add_card_material data-create-url="#{ new_card_path({category_id: @category.id,:format => :json})}"
  svg height="512" viewbox=("0 0 510 510") width="512" xmlns="http://www.w3.org/2000/svg"
    path d=("M255 0C114.8 0 0 114.8 0 255s114.8 255 255 255 255-114.7 255-255S395.3 0 255 0zM382.5 280.5h-102v102h-51v-102h-102v-51h102v-102h51v102h102V280.5z") fill="#ff6e00"
.create_card.material data-create-url="#{ new_card_path({category_id: @category.id,:format => :json})}"

app/views/cards/_card.slim
- card ||= @card

.card class=(card.big? ? 'double' : '') data-card-id=card.id data-priority=card.priority data-edit-url=edit_card_path(card.id, format: :json)
  - unless card.image.blank?
    .card-photo class=(card&.image_style ? 'vertical' : '')
      = image_tag card.image
  .card-content
    .card-header
      h3
        = card.title
    .card-items
      - card.card_items.each do |item|
        = render 'main/card_item.html', locals: { item: item }
    .card-tags
      = card.tags.map{|tag| link_to tag.name, search_path(tag: tag.name)}.join(', ').html_safe
    - unless card.card_logo.blank?
      .card-logo
        = image_tag card.card_logo

app/views/cards/_card_item_fields.slim
- card_item = f.object
.card-item
  =f.input :name, :input_html => { :class => 'item-name', placeholder: "Название"}, label: false
  =f.input :meta, :input_html => { :class => 'item-unit', placeholder: "Вес; Количество;"}, label: false
  - if card_item.id.blank?
    -key = [*('a'..'z'),*('A'..'Z')].shuffle[0,50].join
    =f.input :temp_key, input_html: {value: key}, as: 'hidden'
    div class=("dropzone subimg-upload #{card_item.card.image_style ? 'vertical' : '' if card_item.card}") data-action=create_image_path({temp_key: key, type: "image"})
  - else
    =f.input :temp_key, as: 'hidden'
    div class=("dropzone subimg-upload #{card_item.card.image_style ? 'vertical' : '' if card_item.card}")  data-action=update_image_card_path({id: card_item.card.id, type: 'image', card_item: card_item.id})
      - unless card_item.image.blank?
        .card-sub-photo
          = image_tag card_item.image, data: {name: card_item.image.url.split('/').pop(), size: card_item.image.size}
  .item-price
    - unless card_item.image.blank?
      .remove-subimg-wrapper
        a.remove_subimg data-card="#{card_item.card.id}" data-item="#{card_item.id}" href="#"  
          |Удалить изображение
    =f.input :price, :input_html => { :class => 'item-price-value', placeholder: "Цена"}, label: false
    |&thinsp;
    span.rouble
      |₽
    =f.select :units, enum_option_pairs(CardItem, :units), {} ,{ :class => 'item-unit-select item_units_field' }
    a.remove_item href="#"
      |Удалить
  =f.input :vendor_code, :input_html => { :class => 'item-price-value', placeholder: "Артикул"}, label: false
  =f.input :weight, :input_html => { :class => 'item-price-value card-weight-input item_weight_field', placeholder: "Средний вес"}, label: false
  =f.input :id, as: "hidden", :input_html => { :class => 'card_items_id'}
  =f.input :priority, as: "hidden", :input_html => { :class => 'card_items_priority'}

app/views/cards/_form.slim
.card class=(card.big? ? 'double' : '')
  = semantic_form_for card, remote: true, html: { class: "card-form #{card.id.blank? ? 'new_card' : 'update_card'}" } do |f|
    .checkbox-group
      .checkbox
        = f.check_box :image_style
        | Вертикальные изображения
      .checkbox
        = f.check_box :size_cd
        | Двойная
    = f.input :category_id, as: 'hidden'
    = f.input :temp_key, as: 'hidden'
    - if !card.id.blank?
      .dropzone.image-upload class=(card&.image_style ? 'vertical' : '') data-action=update_image_card_path(id: card.id, type: 'image')
    - else
      .dropzone.image-upload class=(card&.image_style ? 'vertical' : '') data-action=create_image_path(temp_key: card.temp_key, type: 'image')
    - unless card.image.blank?
      .card-photo
        = image_tag card.image, data: { name: card.image.url.split('/').pop(), size: card.image.size }
      a.remove-image href="#" data-card=card.id
        | Удалить
    .card-content
      = f.input :title, label: false, input_html: { class: 'card-form-title', placeholder: 'Заголовок' }
      #card_items_sortable.card-items
        = f.semantic_fields_for :card_items do |card_item|
          = render 'card_item_fields', f: card_item
        = link_to_add_association 'Добавить', f, :card_items, :'data-association-insertion-node' => '.card-item:last', :'data-association-insertion-method' => 'after'
      = f.text_field :tag_list, label: false, 'data-list': tags, 'data-multiple': '', class: 'card-form-tags awesomplete', placeholder: "#tag, #tag, #tag", value: card.tag_list.join(', ')
      .card-logo
        - unless card.card_logo.blank?
          = image_tag card.card_logo, data: { name: card.card_logo.url.split('/').pop(), size: card.card_logo.size }
      - if card.id.blank?
        .dropzone.logo-upload data-action=create_image_path(temp_key: card.temp_key, type: 'logo')
      - else
        .remove-logo-wrapper
          .dropzone.logo-upload data-action=update_image_card_path(id: card.id, type: 'logo')
        - if card.card_logo.present?
          a.remove_logo href="#" data-card=card.id
      .save-button
        button[type="submit"]
          | Сохранить

app/views/cards/create.slim
= render 'form', card: @card, tags: @tags

app/views/cards/destroy.js.erb
$('.del-icon').bind('ajax:success', function() {
  $(this).parent().fadeOut();
});

app/views/cards/edit.slim
= render 'form', card: @card, tags: @tags